ALTER TABLE users ADD COLUMN phone TEXT;
ALTER TABLE users ADD COLUMN fio TEXT NOT NULL DEFAULT '';
ALTER TABLE users ALTER COLUMN email SET DEFAULT NULL;
ALTER TABLE users ALTER COLUMN password_hash SET DEFAULT '';
CREATE UNIQUE INDEX idx_users_phone ON users(phone) WHERE phone IS NOT NULL;
